menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive

social:
  GitHub: https://github.com/xiangsanliu || fab fa-github

scheme: Gemini

minify: true

darkmode: true

# menu_settings:
#   icons: false
#   badges: true

avatar:
  # Replace the default image and set the url here.
  url: https://cdn.jsdelivr.net/gh/xiangsanliu/images/img/202207010938501.jpeg
  # If true, the avatar will be displayed in circle.
  rounded: true

github_banner:
  enable: true
  permalink: https://github.com/xiangsanliu
  title: Follow me on GitHub


index_with_subtitle: true

# See: https://developers.google.com/search
google_site_verification: bniPdSmMgEATPxhlCBfdEUKcD5gcGMaswG18ouRKQsI

# Bing Webmaster tools verification.
# See: https://www.bing.com/webmasters
bing_site_verification: AB7BC7083C95E758EF81A2BA6B192F9D

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification: code-EQVdXB74wo
